<?php
/**
 * @category   Chirag
 * @package    Chirag_Banner
 * @author     chirag@czargroup.net
 * @copyright  This file was generated by using Module Creator provided by <developer@czargroup.net>
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */

namespace Chirag\Banner\Model\ResourceModel;

class Post extends \Magento\Framework\Model\ResourceModel\Db\AbstractDb
{
    /**
     * Define main table
     */
    protected function _construct()
    {
        $this->_init('chirag_banner_table', 'banner_id');   //here "chirag_banner_table" is table name and "banner_id" is the primary key of custom table
    }
}