<?php
/**
 * @category   Chirag
 * @package    Chirag_Banner
 * @author     chirag@czargroup.net
 * @copyright  This file was generated by using Module Creator provided by <developer@czargroup.net>
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */

namespace Chirag\Banner\Controller\Adminhtml\Post;

class NewAction extends \Chirag\Banner\Controller\Adminhtml\Post
{

    public function execute()
    {
        $this->_forward('edit');
    }
}
